package com.cqut.building.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class ServiceLeaveWords {
	private String id;

	private Date leaveWordsTime;

	private String wxUserId;

	private String userId;

	private Date replyTime;

	private String leaveOrganizationId;

	private String leavePostId;

	private String replyOrganizationId;

	private String replyPostId;

	private String leaveWordsContent;

	private String replyContent;

	public String getReplyOrganizationId() {
		return replyOrganizationId;
	}

	public void setReplyOrganizationId(String replyOrganizationId) {
		this.replyOrganizationId = replyOrganizationId;
	}

	public String getReplyPostId() {
		return replyPostId;
	}

	public void setReplyPostId(String replyPostId) {
		this.replyPostId = replyPostId;
	}

	public String getLeaveOrganizationId() {
		return leaveOrganizationId;
	}

	public void setLeaveOrganizationId(String leaveOrganizationId) {
		this.leaveOrganizationId = leaveOrganizationId;
	}

	public String getLeavePostId() {
		return leavePostId;
	}

	public void setLeavePostId(String leavePostId) {
		this.leavePostId = leavePostId;
	}

	public String getLeaveWordsContent() {
		return leaveWordsContent;
	}

	public void setLeaveWordsContent(String leaveWordsContent) {
		this.leaveWordsContent = leaveWordsContent;
	}

	public String getReplyContent() {
		return replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_leave_words.id
	 * @param id  the value for service_leave_words.id
	 * @mbg.generated  Fri Nov 29 18:30:03 GMT+08:00 2019
	 */
	public void setId(String id) {
		this.id = id;
	}


	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT")
	public Date getLeaveWordsTime() {
		return leaveWordsTime;
	}


	public void setLeaveWordsTime(Date leaveWordsTime) {
		this.leaveWordsTime = leaveWordsTime;
	}


	public String getWxUserId() {
		return wxUserId;
	}


	public void setWxUserId(String wxUserId) {
		this.wxUserId = wxUserId;
	}


	public String getUserId() {
		return userId;
	}


	public void setUserId(String userId) {
		this.userId = userId;
	}

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT")
	public Date getReplyTime() {
		return replyTime;
	}


	public void setReplyTime(Date replyTime) {
		this.replyTime = replyTime;
	}
}